version: '3.8'

services:
  backend:
    build: ./roshan_task
    ports:
      - "8000:8000"  
    volumes:
      - ./roshan_task:/usr/src/app  
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py runserver 0.0.0.0:8000"
    depends_on:
    - cache
  
  cache:
    image: redis:7.0.4
  
  celery:
    build: ./roshan_task
    command: celery -A config worker -l info
    volumes:
      - ./roshan_task/:/usr/src/app/
    depends_on:
      - cache

  celery-beat:
    build: ./roshan_task
    command: celery -A config beat -l info
    volumes:
      - ./roshan_task/:/usr/src/app/
    depends_on:
      - cache
  
