# Generated by Django 5.1.3 on 2024-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.IntegerField(choices=[(1, 'available'), (2, 'unavailable')], default=2, verbose_name='available'),
        ),
    ]
